#!/bin/bash
# Send Signal K notifications by email
# Usage: email [-n] [-l] args...

COMMAND="/usr/bin/mail"
LOGGER="/usr/bin/logger"
LOG=""
MESSAGE=""
MODE="normal"
SUBJECT="Signal K notification"
ADDRESSES=""

if [ $# -eq 0 ]; then
	echo "Send Signal K notifications by email (arguments must be email addresses)"
	exit 0
fi

if hash ${COMMAND} 2>/dev/null ; then
	MESSAGE=$(cat)
	while [ "${1}" != "" ]; do
		case ${1} in
		    -n)	# Dry-run (i.e. don't do anything)
                MODE="dryrun"
                ;;
            -l) # Log activity
                LOG="yes"
                ;;
		    *)  # Process email address arguments
                ADDRESSES="${ADDRESSES} ${1}"
			    ;;
		esac
		shift
	done
    if [ "${LOG}" != "" ]; then
	    logger "signalk-renotifier:email[${MODE}]: \"${MESSAGE}\" => ${COMMAND} -s ${SUBJECT} ${ADDRESSES}"
    fi
    if [ "${MODE}" == "normal" ] ; then
	    echo "${MESSAGE}" | ${COMMAND} -s ${SUBJECT} ${ADDRESSES}
    fi

	exit 0
else
	>&2 echo "required program '${COMMAND}' is not available"
	exit 1
fi

