#!/bin/bash
# Send Signal K notifications by SMS
# Usage: SMS [-n] [-l] args...

COMMAND="/usr/local/bin/gammu"
LOGGER="/usr/bin/logger"
LOG=""
MESSAGE=""
MODE="normal"

if [ $# -eq 0 ]; then
	echo "Send Signal K notifications by SMS (arguments must be phone numbers)"
	exit 0
fi

if hash ${COMMAND} 2>/dev/null ; then
	MESSAGE=$(cat)
	while [ "${1}" != "" ]; do
		case ${1} in
		    -n)	# Dry-run (i.e. don't do anything)
                MODE="dryrun"
                ;;
            -l) # Log activity
                LOG="yes"
                ;;
		    *)  # Process telephone number argument
                if [ "${LOG}" != "" ]; then
				    logger "signalk-renotifier:sms[${MODE}]: \"${MESSAGE}\" => ${COMMAND} sendsms TEXT ${1}"
                fi
			    if [ "${MODE}" == "normal" ] ; then
				    echo "${MESSAGE}" | ${COMMAND} sendsms TEXT ${1}
			    fi
			    ;;
		esac
		shift
	done
	exit 0
else
	>&2 echo "required program '${COMMAND}' is not available"
	exit 1
fi

