#!/bin/bash
# Send Signal K notifications by SMS
# Usage: SMS [-n] [-l] args...

COMMAND="/usr/bin/gammu-smsd-inject"
LOGGER="/usr/bin/logger"
LOG=""
MESSAGE=""
MODE="normal"

if [ $# -eq 0 ]; then
	echo "Send Signal K notifications by SMS (arguments must be phone numbers)"
	exit 0
fi

if hash ${COMMAND} 2>/dev/null ; then
    declare -A DICTIONARY
    while read -r line; do
        TOKEN=${line%%:*}
        VALUE=${line#*:}
        DICTIONARY[${TOKEN}]=${VALUE}
    done <<< "$(cat)"

MESSAGE=$(cat <<END_HEREDOC
${DICTIONARY[STATE]} notification from ${DICTIONARY[VESSEL]}: ${DICTIONARY[MESSAGE]}
END_HEREDOC
)

if hash ${COMMAND} 2>/dev/null ; then
	MESSAGE=$(cat)
	while [ "${1}" != "" ]; do
		case ${1} in
		    -n)	# Dry-run (i.e. don't do anything)
                MODE="dryrun"
                ;;
            -l) # Log activity
                LOG="yes"
                ;;
		    *)  # Process telephone number argument
                if [ "${LOG}" != "" ]; then
				    ${LOGGER} "signalk-renotifier:sms[${MODE}]: ${COMMAND} TEXT ${1} -text \"${MESSAGE}\""
                fi
			    if [ "${MODE}" == "normal" ] ; then
				    ${COMMAND} TEXT ${1} -text "${MESSAGE}"
			    fi
			    ;;
		esac
		shift
	done
	exit 0
else
	>&2 echo "required program '${COMMAND}' is not available"
	exit 1
fi

